name: Compile Component & Logix Lists

on:
  push:
    branches: [ "main", "dev" ]
  # Allows you to run this workflow manually from the Actions tab. DO NOT REMOVE.
  workflow_dispatch:
    branches: [ "main", "dev" ]

jobs:
  generate-component-list:
    name: "Generate Lists"
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Download Neos
      shell: pwsh
      run: |
        New-Item -Type Directory NeosVR
        cd NeosVR
        $web = [System.Net.WebClient]::new()
        # $web.DownloadFile("https://www.7-zip.org/a/7zr.exe","$PWD\7zr.exe")
        $cvstring = $web.DownloadString('https://cloudxstorage.blob.core.windows.net/install/Pro/Public')
        $web.DownloadFile("https://assets.neos.com/install/Pro/Data/$cvstring.7z","$env:TEMP\neosupdate.7z")

    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: unzip -qq $env:TEMP\neosupdate.7z -d $PWD\NeosVR

    # Sets up .NET Core 6.0.x
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    # Runs our custom cs file to generate the list.
    - name: Build Script
      id: generate-list
      run: |
        dotnet build
        dotnet run

    # Commits the changes to the repo.
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Component List"
        git pull origin main
        git add lists/ComponentList.txt
        git add lists/LogixList.txt
        git commit -m "Automatic component list compile" || true

    # Pushes the changes to the repo.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
