name: SteamCMDTest

on:
  # I wondr if this can be triggered automatically when Neos Updates? Worth a lot of research.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab. Do not remove.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Lets get SteamCMD downloaded.
    - name: Install SteamCMD
      uses: CyberAndrii/setup-steamcmd@v1

      # And now to download NeosVR
    - name: Install NeosVR
      run: steamcmd +login ${{ secrets.PASSCODE }} +app_update 740250 -beta headless-client -betapassword nSRDU739h17f9Qce6ZeZ validate +force_install_dir $HOME/ +quit

# Probably not needed, but will stay for further testing.
#    - name: Install Mono
#      run: sudo apt install mono-devel

# Realized I don't need to start Neos, leaving it for the same reason as Mono
#    - name: Run Headless
#      run: $HOME/Steam/steamapps/common/NeosVR/Neos
